trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'my-app' # The name of your Docker image in ACR
  dockerRegistryServiceConnection: 'myacr' # Your Azure Container Registry service connection name
  aksServiceConnection: 'Azure service connection' # Your AKS cluster service connection name
  helmChartPath: 'helm/my-app' # Path to Helm chart in repo

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildJob
    displayName: Build Container
    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: 'app/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

    - task: HelmInstaller@1
      displayName: Install Helm
      inputs:
        helmVersionToInstall: '3.11.0'

- stage: DeployToDev
  displayName: Deploy to Dev
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    displayName: Deploy with Helm to AKS
    environment: 'Dev-aks'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            persistCredentials: true
          - task: HelmInstaller@1
            displayName: Install Helm on Agent
            inputs:
              helmVersionToInstall: '3.11.0'

          - task: HelmDeploy@0
            displayName: Helm Upgrade/Install (Dev)
            inputs:
              azureSubscription: '$(aksServiceConnection)'
              azureResourceGroup: 'demo'
              kubernetesCluster: 'my-aks-cluster'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(System.DefaultWorkingDirectory)/$(helmChartPath)'
              releaseName: 'my-app-dev'
              arguments: '--install -f $(System.DefaultWorkingDirectory)/$(helmChartPath)/values.dev.yaml'
              overrideValues: 'image.tag=$(Build.BuildId)'

- stage: DeployToQA
  displayName: Deploy to QA
  dependsOn: DeployToDev
  condition: succeeded()
  jobs:
  - deployment: DeployQAJob
    displayName: Deploy with Helm to AKS
    environment: 'QA-aks'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            persistCredentials: true
          - task: HelmInstaller@1
            displayName: Install Helm on Agent
            inputs:
              helmVersionToInstall: '3.11.0'

          - task: HelmDeploy@0
            displayName: Helm Upgrade/Install (QA)
            inputs:
              azureSubscription: '$(aksServiceConnection)'
              azureResourceGroup: 'demo'
              kubernetesCluster: 'my-aks-cluster'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(System.DefaultWorkingDirectory)/$(helmChartPath)'
              releaseName: 'my-app-qa'
              arguments: '--install -f $(System.DefaultWorkingDirectory)/$(helmChartPath)/values.qa.yaml'
              overrideValues: 'image.tag=$(Build.BuildId)'
